DurbanHarbourControlServices/Models/ErrorViewModel.cs
namespace DurbanHarbourControlServices.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DurbanHarbourControlServices/Models/VesselListModel.cs
using SharedLib.Models;
using System.Collections.Generic;

namespace DurbanHarbourControlServices.Models
{
    public class VesselListModel
    {
        public List<VesselModel> list { get; set; }
    }
}

DurbanHarbourControlServices/Controllers/HarbourController.cs
using DurbanHarbourControlServices.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using SharedLib.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;

namespace DurbanHarbourControlServices.Controllers
{
    public class HarbourController : Controller
    {
        private readonly ILogger<HarbourController> _logger;

        public HarbourController(ILogger<HarbourController> logger)
        {
            _logger = logger;
        }

        public IActionResult Harbour()
        {
            IEnumerable<VesselModel> vessels = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44390/api/Vessels/"); //TODO: Change URL and Port
                //HTTP GET
                var responseTask = client.GetAsync("ActiveVessels");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsStringAsync();
                    readTask.Wait();

                    vessels = JsonConvert.DeserializeObject<IEnumerable<VesselModel>>(readTask.Result);
                }
                else //web api sent error response
                {
                    vessels = new List<VesselModel>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }

            VesselListModel vl = new VesselListModel();
            vl.list = vessels.ToList();

            return View(vl);
        }
    }
}

DurbanHarbourControlServices/Views/Harbour/Harbour.cshtml
@model DurbanHarbourControlServices.Models.VesselListModel;
@{
    ViewData["Title"] = "Harbour Control";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="container-fluid col-12">
        <h1>@ViewData["Title"]</h1>
    </div>
</div>
<div class="row section">
    <div class="container col-8">
        <div id="radar">
            <div id="rad"></div>
            @foreach (SharedLib.Models.VesselModel vessel in Model.list)
            {
                <div class="obj tooltip @vessel.Type.ToString()" data-x="@vessel.Lat" data-y="@vessel.Long">
                    <span class="tooltiptext">@vessel.Name</span>
                </div>
            }
        </div>
    </div>
    <div class="container col-4">
    </div>
</div>

@section Scripts{
    <script src="~/js/harbour.js" asp-append-version="true"></script>
}

DurbanHarbourControlServices/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Durban Harbour Control Services</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Harbour" asp-action="Harbour">
                    <span class="material-icons">
                        directions_boat
                    </span> Durban Harbour Control Services
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <span class="material-icons">
                                compass_calibration
                            </span>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Harbour" asp-action="Harbour">
                                Harbour Control
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="main-wrapper">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Durban Harbour Control Services - <a asp-area="" asp-controller="Harbour" asp-action="Harbour">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>